### ISSUE TITLE
move card_rules.rb  to yaml file

### ISSUE THREAD

**Issue by Fivell** [Fivell/credit_card_validations#20]
CardRules module doesn't contain logic so it might be better to use YAML file for storing all the data

**Comment by yazinsai** [comment]
Definitely sounds like a good idea .. right now, after adding the card name, it looks like:

```ruby
self.rules = {
        visa: [
            "Visa",
            {length: [13, 16], prefixes: ['4']}
        ],
       ...
```

If we're going to do this anyway, might as well switch directly to YAML.

**Comment by Fivell** [comment]
@yazinsai , take a look https://gist.github.com/Fivell/b3be638089100d712d9f
what do you think ?

**Comment by yazinsai** [comment]
Looks awesome!

You're right about Visa, if I were to do monkey patch the existing `card_rules` I would've most likely set the values for all of the cards for consistency (otherwise the rules could get ugly)..

Having it in a properly structured yaml like the one you referenced is so much neater..
