### ISSUE TITLE
Belkart

### ISSUE THREAD

**Issue by seongreen** [Fivell/credit_card_validations#48]
Hi, could I add Belkart to this repo ? {length: [16], prefixes: ['9112']}

**Comment by Fivell** [comment]
Hi @seongreen , 
I'm not sure right now about core support of belkart, do not know anything about it. Any official / semi-official links where bin range can be found ?
Anyway  you can do this with
```ruby
CreditCardValidations.add_brand(:belkart, {length: 16, prefixes: ['9112']}, {skip_luhn: true}) #skip luhn or not
```

**Comment by seongreen** [comment]
Well 9 prefixes is using for 'National assignment',  And many Internal bank system use it (Belkart is Belarus for example) I just see that you not using 9 in your gem and think that it's funny idea :) Of course I can use your example, thanks.

**Comment by Fivell** [comment]
@seongreen, I believe for now it is better  to leave it as it is. If we will start adding card brands used for 'National assignment' it  can be buggy for users that are not ready for this.  In common scenario it is used with ActiveModel like 

``` ruby
 validates :number, presence: true, credit_card_number: true
```
If there will be more national cards in future I think it will be good idea to create storages per country, where national cards can be described, and then it will be possible to 

```ruby 
 validates :number, presence: true, credit_card_number: { regional: 'BY' } #or something like this
```
