### ISSUE TITLE
CreditCardValidations.add_brand not working in rails c

### ISSUE THREAD

**Issue by Alxzu** [Fivell/credit_card_validations#68]
Hi, awesome gem!
I'm trying to create my own credit card validation in rails console
```
> CreditCardValidations.add_brand(:oca, { length: 16, prefixes: '589' })
 => :oca? 
> test_card_number = '589826275400212'
> CreditCardValidations::Detector.new(test_card_number).brand
 => nil
> CreditCardValidations::Detector.new(test_card_number).oca?
 => false
```
I'm planning to use it in an initializer, but I can't get it work.

I'm using ruby '2.3.1' and

> gem 'credit_card_validations', '~> 3.2.2'
> gem 'rails', '4.2.6'

Thanks

**Comment by Fivell** [comment]
@Alxzu , length of your card is 15, but rules you described is for 16.

```
 '589826275400212'.length
 => 15 
```
but

```
CreditCardValidations.add_brand(:oca, { length: 16, prefixes: '589' })
```

**Comment by Fivell** [comment]
Also if you need skip luhn check, try 

```
2.2.0 :015 >  CreditCardValidations.add_brand(:oca, { length: 16, prefixes: '589' }, {skip_luhn: true})
 => nil 
2.2.0 :016 > test_card_number = '5898262754002121'
 => "5898262754002121" 
2.2.0 :018 > CreditCardValidations::Detector.new(test_card_number).brand
 => :oca 
```

**Comment by Alxzu** [comment]
Hi, thanks for your reply, I fixed my problem deleting `:maestro` card before creating my new credit card validation, which prefix is '58'

**Comment by Fivell** [comment]
@Alxzu , 👍
