### ISSUE TITLE
American Express brand should be "american_express"

### ISSUE THREAD

**Issue by vanboom** [Fivell/credit_card_validations#92]
ActiveMerchant and every gateway that I am working with expects the brand to be 'american_express' instead of 'amex'.

**Comment by Fivell** [comment]
@vanboom I consider not to change it because of backward compatibility, but you can add `american_express` manually. Something like this might work
```
CreditCardValidations::Detector.delete_brand(:amex)
CreditCardValidations.add_brand(:american_express, {length: 15, prefixes: ['34', '37']})
```
